/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://fnkv5o2jejcvjajevogwezt4ta.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wf642erkzvbjhnschuju6lpvpq",
    "aws_cognito_identity_pool_id": "eu-west-2:f10bcf3d-80c1-42d1-9d30-909e4a8c03f7",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_60WWQyvl9",
    "aws_user_pools_web_client_id": "1rg37ujvqff43hv7rc0fiphaml",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "psk-analytics-app95244-staging",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
